docker_stacks/redmine/plugins/scrum/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      post :update_effort
      get :burndown
      get :burndown_graph
      get :stats
      post :sort
    end
    collection do
      get :burndown_index
      get :stats_index
    end
  end
  post "sprints/change_task_status",
       :controller => :sprints, :action => :change_task_status,
       :as => :sprints_change_task_status

  resources :product_backlog, :shallow => true do
    member do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
      get :check_dependencies
      get :release_plan
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      :controller => :product_backlog, :action => :new_pbi,
      :as => :product_backlog_new_pbi

  get "scrum/stats",
      :controller => :scrum, :action => :stats,
      :as => :scrum_stats

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/remaining_story_points",
     :controller => :scrum, :action => :change_remaining_story_points,
     :as => :change_remaining_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/pending_efforts",
     :controller => :scrum, :action => :change_pending_efforts,
     :as => :change_pending_efforts
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
get "issues/:id/time_entry",
     :controller => :scrum, :action => :new_time_entry,
     :as => :new_scrum_time_entry
post "issues/:id/time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_scrum_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     :controller => :scrum, :action => :new_pbi,
     :as => :new_pbi
post "scrum/:sprint_id/create_pbi",
     :controller => :scrum, :action => :create_pbi,
     :as => :create_pbi
get "scrum/:pbi_id/new/:tracker_id",
    :controller => :scrum, :action => :new_task,
    :as => :new_task
post "scrum/:pbi_id/create_task",
     :controller => :scrum, :action => :create_task,
     :as => :create_task
get "scrum/:pbi_id/edit_pbi",
    :controller => :scrum, :action => :edit_pbi,
    :as => :edit_pbi
post "scrum/:pbi_id/update_pbi",
     :controller => :scrum, :action => :update_pbi,
     :as => :update_pbi
get "scrum/:pbi_id/move/:position",
    :controller => :scrum, :action => :move_pbi,
    :as => :move_pbi
get "scrum/:id/edit_task",
    :controller => :scrum, :action => :edit_task,
    :as => :edit_task
post "scrum/:id/update_task",
     :controller => :scrum, :action => :update_task,
     :as => :update_task
post "scrum/:pbi_id/move_to_last_sprint",
     :controller => :scrum, :action => :move_to_last_sprint,
     :as => :move_to_last_sprint
post "scrum/:sprint_id/move_not_closed_pbis_to_last_sprint",
     :controller => :scrum, :action => :move_not_closed_pbis_to_last_sprint,
     :as => :move_not_closed_pbis_to_last_sprint
post "scrum/:pbi_id/move_to_product_backlog",
     :controller => :scrum, :action => :move_to_product_backlog,
     :as => :move_to_product_backlog

docker_stacks/redmine/plugins/scrum/app/views/projects/settings/_product_backlogs.html.erb
<div class="contextual scrum-menu">
  <%= link_to(l(:label_product_backlog_new),
              new_project_sprint_path(@project, :back_url => '', :create_product_backlog => true),
              :class => 'icon icon-add') if User.current.allowed_to?(:manage_sprints, @project) %>
  <%= render_scrum_help('product_backlogs') %>
</div>

<%- if @project.product_backlogs.empty? -%>
  <p class="nodata"><%= l(:label_no_data) %></p>
<%- else -%>
  <table class="list">
    <thead>
      <tr>
        <th><%= l(:field_name) %></th>
        <th><%= l(:field_status) %></th>
        <th><%= l(:field_shared) %></th>
        <th><%= l(:label_pbi_plural) %></th>
        <th style="width:15%"></th>
      </tr>
    </thead>
    <tbody>
      <% for sprint in @project.product_backlogs %>
        <tr class="version <%= cycle 'odd', 'even' %> <%= sprint.status %>">
          <td><%= link_to(h(sprint.name), product_backlog_path(sprint)) %></td>
          <td class="status"><%= l("label_sprint_status_#{sprint.status}") %></td>
          <td align="center"><%= checked_image sprint.shared %></td>
          <td align="center"><%= sprint.pbis.count %></td>
          <td class="buttons">
            <%- if User.current.allowed_to?(:manage_sprints, @project) -%>
              <%= link_to l(:button_edit), edit_sprint_path(sprint),
                          :class => 'icon icon-edit' %>
              <%= delete_link sprint_path(sprint) %>
            <%- end -%>
          </td>
        </tr>
      <% end; reset_cycle %>
    <tbody>
  </table>
<%- end -%>

docker_stacks/redmine/plugins/scrum/app/views/projects/settings/_sprints.html.erb
<div class="contextual scrum-menu">
  <%= link_to(l(:label_sprint_new), new_project_sprint_path(@project, :back_url => ''),
              :class => 'icon icon-add') if User.current.allowed_to?(:manage_sprints, @project) %>
  <%= render_scrum_help('sprints') %>
</div>

<%- if @project.sprints.empty? -%>
  <p class="nodata"><%= l(:label_no_data) %></p>
<%- else -%>
  <table class="list">
    <thead>
      <tr>
        <th><%= l(:field_name) %></th>
        <th><%= l(:field_start_date) %></th>
        <th><%= l(:field_end_date) %></th>
        <th><%= l(:field_status) %></th>
        <th><%= l(:field_shared) %></th>
        <th><%= l(:label_pbi_plural) %></th>
        <th><%= l(:label_task_plural) %></th>
        <th style="width:15%"></th>
      </tr>
    </thead>
    <tbody>
      <% for sprint in @project.sprints %>
        <tr class="version <%= cycle 'odd', 'even' %> <%= sprint.status %>">
          <td><%= link_to(h(sprint.name), sprint.is_product_backlog? ? product_backlog_path(sprint) : sprint) %></td>
          <td align="center"><%= format_date(sprint.sprint_start_date) %></td>
          <td align="center"><%= format_date(sprint.sprint_end_date) %></td>
          <td class="status"><%= l("label_sprint_status_#{sprint.status}") %></td>
          <td align="center"><%= checked_image sprint.shared %></td>
          <td align="center"><%= sprint.pbis.count %></td>
          <td align="center"><%= sprint.tasks.count %></td>
          <td class="buttons">
            <%- if User.current.allowed_to?(:manage_sprints, @project) -%>
              <%= link_to l(:label_edit_effort), edit_effort_sprint_path(sprint),
                          :class => 'icon icon-time-add' %>
              <%= link_to l(:button_edit), edit_sprint_path(sprint),
                          :class => 'icon icon-edit' %>
              <%= delete_link sprint_path(sprint) %>
            <%- end -%>
          </td>
        </tr>
      <% end; reset_cycle %>
    <tbody>
  </table>
<%- end -%>